### PR TITLE
Compilation works on Linux (LLVM 15)

### PR DESCRIPTION
**Pull request by mrexodia**
Just some local experiments in a Docker image if anyone is interested (not ready for merging obviously)...

### CODE REVIEW

**Comment by mrexodia** [comment]
Unfortunately this crashes right away when lifting a `mov` instruction: `140001000  4889c8             mov     rax, rcx`

[liftme.exe.zip](https://github.com/NaC-L/Mergen/files/14628670/liftme.exe.zip)

I'll have to compile this with address sanitizer and see what's going on in more detail...

**Comment by NaC-L** [comment]
Only reason I could think is apparently I havent implement `jnb` instruction, its implemented now and binary is lifted on windows correctly right now.

**Comment by mrexodia** [comment]
Yeah it doesn’t even get there, it crashes in the mov right away with some memory corruption error on the command line. I’ll investigate it properly tomorrow and see what could be going on. My LLVM is also at 15, so that might be an issue as well…

**Comment by NaC-L** [comment]
I figured out why crash is happening, I'll merge this and take care of it. Thanks for your contributions!

**Comment by NaC-L** [comment]
I figured out it crashes, can you update to latest version so I can merge your branch?

**Comment by mrexodia** [comment]
Yes, I will rebase it!

**Comment by mrexodia** [comment]
Done, I rebased on the latest development branch and removed the CMake changes. I think the CMake needs to be rewritten fully, but I don't have time for this now...

**Comment by NaC-L** [comment]
LGTM, I'll push the commit to fix the crash in a bit. Thanks for your contributions!

**Pull request merged**
